### PR TITLE
Journal/Tutorial/Resource Rough Drafts

### PR DESCRIPTION
**Pull request by ericksonk**

### CODE REVIEW

**Comment by rosalsm** [comment]
good tutorial. Today I have 2 merge conflicts :+1:

**Comment by cmauban** [comment]
Great topics this week! I vote for Nerdary into to APIs! :+1:

**Comment by karjac14** [comment]
Great resource on API! :+1: 

zzzz

**Comment by jeffworley** [comment]
great topics!  I will def have to give these a read as we continue to work with API's and MVC :+1:

**Comment by drumslayert** [comment]
Great work Kristine! I like the comparison of an API to a waiter. It's a good way to visualize it.

**Pull request merged**
