### PR TITLE
Journal Week 2: Final Draft

### PR DESCRIPTION
**Pull request by ericksonk**

### CODE REVIEW

**Comment by ericquayson** [comment]
:+1: Great Journal, Kristine. I may need your assistance in writing the JavaScript for the NestedAccordion. haha

**Comment by jeremyrist** [comment]
:+1: On to the next! I wish I had your confidence with querySelector and querySelectorAll

**Comment by Ricecoder** [comment]
That's great that you're comfortable with QS and QSA! Looping through them was not an easy thing to do so good job! :+1:

**Comment by s4dmw** [comment]
looks great!  :+1: 

I agree with your take on Pseudo coding. It definitely helps break things down in to more manageable tasks.

**Pull request merged**
